#ifndef KERNEL_TIMER_H
#define KERNEL_TIMER_H

#include <stdint.h>

/*
 * Initialize the kernel's generic timer accounting.
 *
 * frequency_hz must be the ACTUAL frequency generated by the
 * underlying timer hardware.
 */
void timer_initialize(uint32_t frequency_hz);

/*
 * Called exactly once for every hardware timer tick.
 *
 * This is called from interrupt context.
 */
void timer_handle_tick(void);

/*
 * Number of hardware ticks since timer initialization.
 */
uint64_t timer_ticks(void);

/*
 * Actual timer frequency in Hz.
 */
uint32_t timer_frequency(void);

/*
 * Approximate uptime in milliseconds.
 */
uint64_t timer_uptime_ms(void);

/*
 * Convert milliseconds to timer ticks, rounding upward.
 *
 * Useful later for sleep queues and timeouts.
 */
uint64_t timer_ms_to_ticks(uint64_t milliseconds);

#endif